variables:
  DH_REPOSITORY: zammad

before_script:
  - docker info

build_image:
  only:
    - master
    - develop
    - tags
  script:
    - docker build --no-cache --pull -t zammad/zammad:latest .
    - docker login -u zammad -p $DOCKERHUB_PW
    - docker push zammad/zammad:latest
